"""fix username str

Revision ID: 9934c6c6f941
Revises: 
Create Date: 2026-01-04 19:53:41.825044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9934c6c6f941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('passhash', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passhash'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_role_name'), 'users', ['role_name'], unique=False)
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['users.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tokens_user_name'), 'tokens', ['user_name'], unique=False)
    op.create_table('user_account',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('User_id', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account')
    op.drop_index(op.f('ix_tokens_user_name'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_users_role_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('role')
    op.drop_table('accounts')
    # ### end Alembic commands ###
